// AUTO-GENERATED by geojson_to_arduino.py — DO NOT EDIT
// Timezone lookup by GPS coordinates for Arduino / ESP32 / ESP8266
//
// Include order in your .ino:
//   #include "timezone_data.h"   // <-- FIRST (defines PROGMEM stubs + data)
//   #include "timezone_lookup.h" // <-- SECOND
//
// Usage:
//   TzResult r = tz_lookup(48.8566f, 2.3522f, 2026, 3, 29, 3, 0);
//   if (r.valid) {
//     Serial.println(r.country);      // "FR"
//     Serial.println(r.abbr);         // "CEST"
//     Serial.print(r.utc_offset_h);   // 2.0  (float, hours)
//   }
#pragma once
// timezone_data.h must be included BEFORE this file — it defines
// TzZone, TZ_ZONES, TZ_POINTS, TZ_ZONE_COUNT and all PROGMEM helpers.
#include <stdint.h>
#include <string.h>

// ── Result structure ────────────────────────────────────────────
typedef struct {
  uint8_t  valid;           // 1 = found, 0 = no zone at these coordinates
  char     country[4];      // ISO 3166-1 alpha-2, e.g. "DE"
  char     tzid[40];        // IANA id, e.g. "Europe/Berlin"
  char     abbr[10];        // time abbreviation, e.g. "CEST"
  float    utc_offset_h;    // current UTC offset in hours, e.g. 2.0
  uint8_t  is_dst;          // 1 if DST is currently active
} TzResult;

// ── PROGMEM helpers ─────────────────────────────────────────────
static inline int16_t _tz_pt(uint16_t pair_idx, uint8_t component) {
    return (int16_t)pgm_read_word(&TZ_POINTS[pair_idx * 2 + component]);
}

static inline void _tz_read_zone(uint16_t i, TzZone* out) {
    memcpy_P(out, &TZ_ZONES[i], sizeof(TzZone));
}

// ── DST active check ────────────────────────────────────────────
static uint8_t _tz_rule_day(const uint8_t rule[5], uint16_t year) {
    uint8_t month = rule[0];
    uint8_t week  = rule[1];
    uint8_t dow   = rule[2];  // POSIX: 0=Sun, 1=Mon ... 6=Sat

    uint8_t m = month;
    uint16_t y = year;
    if (m < 3) { m += 12; y--; }
    uint8_t first_dow = (uint8_t)((1 + (13*(m+1))/5 + y + y/4 - y/100 + y/400) % 7);

    int8_t diff = (int8_t)dow - (int8_t)first_dow;
    if (diff < 0) diff += 7;
    uint8_t day = 1 + (uint8_t)diff;

    if (week == 5) {
        static const uint8_t mdays[13] = {0,31,28,31,30,31,30,31,31,30,31,30,31};
        uint8_t max_day = mdays[month];
        if (month == 2 && ((year%4==0 && year%100!=0) || year%400==0)) max_day = 29;
        while (day + 7 <= max_day) day += 7;
    } else {
        day += 7 * (week - 1);
    }
    return day;
}

static uint8_t _tz_is_dst(const TzZone* z,
                           uint16_t year, uint8_t month, uint8_t mday,
                           uint8_t hour, uint8_t minute) {
    if (!z->has_dst) return 0;

    const uint8_t* rs = z->dst_start;
    const uint8_t* re = z->dst_end;
    if (rs[0] == 0 || re[0] == 0) return 0;

    uint8_t start_day = _tz_rule_day(rs, year);
    uint8_t end_day   = _tz_rule_day(re, year);

    static const uint16_t mstart[13] = {
        0, 0, 31, 59, 90, 120, 151, 181, 212, 243, 273, 304, 334
    };
    uint32_t now   = (uint32_t)(mstart[month]   + mday      - 1) * 1440 + hour * 60 + minute;
    uint32_t t_on  = (uint32_t)(mstart[rs[0]]   + start_day - 1) * 1440 + rs[3] * 60 + rs[4];
    uint32_t t_off = (uint32_t)(mstart[re[0]]   + end_day   - 1) * 1440 + re[3] * 60 + re[4];

    if (t_on < t_off) {
        return (now >= t_on && now < t_off) ? 1 : 0;
    } else {
        return (now >= t_on || now < t_off) ? 1 : 0;
    }
}

// ── Ray-casting point-in-polygon ────────────────────────────────
static uint8_t _tz_pip_ring(int32_t ilon, int32_t ilat,
                             uint16_t pt_start, uint16_t pt_end) {
    uint8_t  inside = 0;
    uint16_t n = pt_end - pt_start;
    if (n < 3) return 0;

    uint16_t j = n - 1;
    for (uint16_t i = 0; i < n; i++) {
        int32_t xi = _tz_pt(pt_start + i, 0);
        int32_t yi = _tz_pt(pt_start + i, 1);
        int32_t xj = _tz_pt(pt_start + j, 0);
        int32_t yj = _tz_pt(pt_start + j, 1);

        if (xi == 32767 || xj == 32767) { j = i; continue; }

        if (((yi > ilat) != (yj > ilat)) &&
            (ilon < (xj - xi) * (ilat - yi) / (yj - yi) + xi)) {
            inside ^= 1;
        }
        j = i;
    }
    return inside;
}

static uint8_t _tz_point_in_zone(int32_t ilon, int32_t ilat, const TzZone* z) {
    uint16_t ps = z->pt_start;
    uint16_t pe = z->pt_end;

    if (ilon < z->bbox[0] || ilon > z->bbox[2]) return 0;
    if (ilat < z->bbox[1] || ilat > z->bbox[3]) return 0;

    uint16_t ring_start = ps;
    uint8_t  in_any     = 0;

    for (uint16_t k = ps; k < pe; k++) {
        int16_t x = _tz_pt(k, 0);
        int16_t y = _tz_pt(k, 1);
        if (x == 32767 && y == 32767) {
            if (_tz_pip_ring(ilon, ilat, ring_start, k)) in_any = 1;
            ring_start = k + 1;
        }
    }
    if (_tz_pip_ring(ilon, ilat, ring_start, pe)) in_any = 1;
    return in_any;
}

// ── Public API ──────────────────────────────────────────────────
/**
 * tz_lookup — find timezone for GPS coordinates.
 *
 * @param lat      Latitude  (+N / -S)
 * @param lon      Longitude (+E / -W)
 * @param year     4-digit year,  e.g. 2026
 * @param month    Month 1-12
 * @param mday     Day of month 1-31
 * @param hour     Hour 0-23  (UTC)
 * @param minute   Minute 0-59
 * @return TzResult  (.valid==0 if point is in no timezone polygon)
 *
 * Example:
 *   TzResult r = tz_lookup(52.52f, 13.405f, 2026, 6, 15, 10, 0);
 *   // r.country="DE", r.abbr="CEST", r.utc_offset_h=2.0, r.is_dst=1
 */
static TzResult tz_lookup(float lat, float lon,
                           uint16_t year, uint8_t month, uint8_t mday,
                           uint8_t hour, uint8_t minute) {
    TzResult result;
    memset(&result, 0, sizeof(result));

    int32_t ilon = (int32_t)(lon * 100.0f + (lon >= 0 ? 0.5f : -0.5f));
    int32_t ilat = (int32_t)(lat * 100.0f + (lat >= 0 ? 0.5f : -0.5f));

    TzZone z;
    for (uint16_t i = 0; i < TZ_ZONE_COUNT; i++) {
        _tz_read_zone(i, &z);
        if (!_tz_point_in_zone(ilon, ilat, &z)) continue;

        result.valid = 1;
        strncpy(result.country, z.country, sizeof(result.country) - 1);
        strncpy(result.tzid,    z.tzid,    sizeof(result.tzid)    - 1);

        uint8_t dst_active  = _tz_is_dst(&z, year, month, mday, hour, minute);
        result.is_dst       = dst_active;
        int16_t off_raw     = dst_active ? z.utc_dst : z.utc_std;
        result.utc_offset_h = off_raw / 100.0f;
        strncpy(result.abbr,
                dst_active ? z.abbr_dst : z.abbr_std,
                sizeof(result.abbr) - 1);
        return result;
    }
    return result;  // valid == 0
}
