#!/usr/bin/env python3
"""
geojson_to_arduino.py
=====================
Converts timezones_dst.geojson → two Arduino header files:

  timezone_data.h      — timezone data in PROGMEM (Flash)
  timezone_lookup.h    — coordinate lookup algorithm

Usage:
    python geojson_to_arduino.py [--input timezones_dst.geojson]
                                 [--out-data timezone_data.h]
                                 [--out-lookup timezone_lookup.h]
                                 [--max-pts 120]

Platform Flash limits:
    Arduino UNO/Nano : ~32 KB  — only feasible with heavily simplified zones
    Arduino Mega     : ~256 KB — sufficient for most zones
    ESP8266          : ~1 MB   — comfortable
    ESP32            : ~4 MB   — no practical limit

Coordinates are stored as int16 (× 100), giving ~1.1 km precision at the equator.
UTC offsets are stored as int16 (× 100) to cover fractional zones
such as India (+5:30 → 550) and Nepal (+5:45 → 575).
"""

import argparse
import json
import sys
from pathlib import Path


# ─────────────────────────────────────────────────────────────────
# Helper functions
# ─────────────────────────────────────────────────────────────────

def flatten_rings(geometry: dict) -> list[list[tuple[float, float]]]:
    """Extracts all outer rings from a Polygon or MultiPolygon."""
    rings = []
    gtype = geometry.get("type", "")
    coords = geometry.get("coordinates", [])
    if gtype == "Polygon":
        if coords:
            rings.append(coords[0])           # outer ring only
    elif gtype == "MultiPolygon":
        for poly in coords:
            if poly:
                rings.append(poly[0])
    return rings


def bbox_of_ring(ring) -> tuple[float, float, float, float]:
    """(lon_min, lat_min, lon_max, lat_max)"""
    lons = [p[0] for p in ring]
    lats = [p[1] for p in ring]
    return min(lons), min(lats), max(lons), max(lats)


def offset_to_int(h: float) -> int:
    """UTC offset in hours → int16 × 100 (covers ±14 h and fractional zones)."""
    return int(round(h * 100))


def parse_posix_rule(rule: str | None) -> tuple[int, int, int, int, int]:
    """
    Parses a POSIX rule Mm.w.d/hh:mm → (month, week, dow, hour, minute).
    Returns (0,0,0,0,0) if rule is None or unrecognised.
    """
    if not rule:
        return (0, 0, 0, 0, 0)
    try:
        # format: M3.5.0/02:00
        m_part, time_part = rule.split("/")
        m_part = m_part.lstrip("M")
        month, week, dow = (int(x) for x in m_part.split("."))
        if ":" in time_part:
            hh, mm = (int(x) for x in time_part.split(":"))
        else:
            hh, mm = int(time_part), 0
        return (month, week, dow, hh, mm)
    except Exception:
        return (0, 0, 0, 0, 0)


def c_str(s: str, max_len: int) -> str:
    """Truncates a string and escapes it for a C string literal."""
    s = s[:max_len - 1].replace('"', '\\"').replace('\\', '\\\\')
    return s


def chunks(lst, n):
    for i in range(0, len(lst), n):
        yield lst[i:i + n]


# ─────────────────────────────────────────────────────────────────
# Generate timezone_data.h
# ─────────────────────────────────────────────────────────────────

RING_SEP = (32767, 32767)   # sentinel value separating rings within one zone

def build_data_header(features: list, max_pts: int) -> str:
    lines = []
    lines.append("// AUTO-GENERATED by geojson_to_arduino.py — DO NOT EDIT")
    lines.append("// Timezone boundary data in PROGMEM (Flash)")
    lines.append("//")
    lines.append("// Point encoding: int16, value = coordinate × 100")
    lines.append("// UTC offset encoding: int16, value = hours × 100")
    lines.append("//   e.g. India +5:30 → 550, Nepal +5:45 → 575")
    lines.append("// DST rule encoding: uint8[5] = {month, week, dow, hour, minute}")
    lines.append("//   POSIX Mm.w.d/hh:mm, week=5 means 'last'")
    lines.append("#pragma once")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append("// Platform detection: AVR (UNO/Mega), ESP32/ESP8266, or desktop")
    lines.append("#if defined(ARDUINO)")
    lines.append("#  if defined(__AVR__)")
    lines.append("#    include <avr/pgmspace.h>")
    lines.append("#  elif defined(ESP8266) || defined(ESP32)")
    lines.append("#    include <pgmspace.h>")
    lines.append("#  else")
    lines.append("//   Other Arduino-compatible boards (RP2040, STM32, SAMD, Teensy...)")
    lines.append("//   pgmspace.h is usually not needed; PROGMEM is a no-op")
    lines.append("#    ifndef PROGMEM")
    lines.append("#      define PROGMEM")
    lines.append("#    endif")
    lines.append("#    ifndef pgm_read_byte")
    lines.append("#      define pgm_read_byte(addr)   (*(const uint8_t*)(addr))")
    lines.append("#    endif")
    lines.append("#    ifndef pgm_read_word")
    lines.append("#      define pgm_read_word(addr)   (*(const uint16_t*)(addr))")
    lines.append("#    endif")
    lines.append("#    ifndef pgm_read_dword")
    lines.append("#      define pgm_read_dword(addr)  (*(const uint32_t*)(addr))")
    lines.append("#    endif")
    lines.append("#    ifndef memcpy_P")
    lines.append("#      define memcpy_P memcpy")
    lines.append("#    endif")
    lines.append("#  endif")
    lines.append("#else")
    lines.append("// Desktop / unit-test build")
    lines.append("#  ifndef PROGMEM")
    lines.append("#    define PROGMEM")
    lines.append("#  endif")
    lines.append("#  ifndef pgm_read_byte")
    lines.append("#    define pgm_read_byte(addr)   (*(const uint8_t*)(addr))")
    lines.append("#  endif")
    lines.append("#  ifndef pgm_read_word")
    lines.append("#    define pgm_read_word(addr)   (*(const uint16_t*)(addr))")
    lines.append("#  endif")
    lines.append("#  ifndef pgm_read_dword")
    lines.append("#    define pgm_read_dword(addr)  (*(const uint32_t*)(addr))")
    lines.append("#  endif")
    lines.append("#  ifndef memcpy_P")
    lines.append("#    include <string.h>")
    lines.append("#    define memcpy_P memcpy")
    lines.append("#  endif")
    lines.append("#endif")
    lines.append("#ifndef pgm_read_int16")
    lines.append("static inline int16_t pgm_read_int16(const void* a){return *(const int16_t*)(a);}")
    lines.append("#endif")
    lines.append("")

    all_points  = []   # all points in order, indexed into the global array
    zone_metas  = []   # per-zone metadata

    skipped = 0

    for feat in features:
        props   = feat.get("properties", {}) or {}
        geom    = feat.get("geometry")
        tzid    = props.get("tzid", "")
        country = props.get("country", "XX")

        if not geom or not tzid:
            continue

        rings = flatten_rings(geom)
        if not rings:
            continue

        # Global bounding box for the zone (union of all rings)
        all_lons, all_lats = [], []
        ring_data = []   # list of [(ix, iy)] per ring

        for ring in rings:
            pts = [(p[0], p[1]) for p in ring]
            if len(pts) < 3:
                continue
            # Uniform decimation to max_pts points
            if len(pts) > max_pts:
                step  = len(pts) / max_pts
                pts   = [pts[int(i * step)] for i in range(max_pts)]
            # Remove the duplicate closing point of a closed ring
            if pts and pts[0] == pts[-1]:
                pts = pts[:-1]
            if len(pts) < 3:
                continue

            ix_iy = [(int(round(x * 100)), int(round(y * 100))) for x, y in pts]
            all_lons.extend(x for x, _ in ix_iy)
            all_lats.extend(y for _, y in ix_iy)
            ring_data.append(ix_iy)

        if not ring_data:
            skipped += 1
            continue

        bbox = (min(all_lons), min(all_lats), max(all_lons), max(all_lats))

        # Write points into the global array; rings are separated by RING_SEP
        start_idx = len(all_points)
        for i, ring_pts in enumerate(ring_data):
            all_points.extend(ring_pts)
            if i < len(ring_data) - 1:
                all_points.append(RING_SEP)   # ring separator

        end_idx = len(all_points)

        # DST metadata
        has_dst       = bool(props.get("has_dst", False))
        utc_std       = offset_to_int(props.get("utc_offset_std", 0.0))
        utc_dst       = offset_to_int(props.get("utc_offset_dst", 0.0))
        dst_off       = offset_to_int(props.get("dst_offset_hours", 0.0))
        abbr_std      = c_str(props.get("abbr_std", ""), 10)
        abbr_dst      = c_str(props.get("abbr_dst", ""), 10)
        dst_start     = parse_posix_rule(props.get("dst_start"))
        dst_end       = parse_posix_rule(props.get("dst_end"))
        tzid_s        = c_str(tzid, 40)
        country_s     = c_str(country, 4)

        zone_metas.append({
            "tzid":       tzid_s,
            "country":    country_s,
            "bbox":       bbox,
            "start_idx":  start_idx,
            "end_idx":    end_idx,
            "ring_count": len(ring_data),
            "has_dst":    has_dst,
            "utc_std":    utc_std,
            "utc_dst":    utc_dst,
            "dst_off":    dst_off,
            "abbr_std":   abbr_std,
            "abbr_dst":   abbr_dst,
            "dst_start":  dst_start,
            "dst_end":    dst_end,
        })

    if skipped:
        print(f"  ⚠ Zones skipped (no geometry): {skipped}", file=sys.stderr)

    total_pts   = len(all_points)
    total_zones = len(zone_metas)
    data_kb     = (total_pts * 4 + total_zones * 90) / 1024

    print(f"  Zones:  {total_zones}")
    print(f"  Points: {total_pts}")
    print(f"  ~Flash: {data_kb:.1f} KB")

    # ── Global point array ───────────────────────────────────────
    lines.append(f"// Total zones: {total_zones},  total coordinate pairs: {total_pts}")
    lines.append(f"// Estimated Flash usage: ~{data_kb:.0f} KB")
    lines.append(f"#define TZ_ZONE_COUNT {total_zones}")
    lines.append(f"#define TZ_POINT_COUNT {total_pts}")
    lines.append("")

    # Point array: interleaved x, y as int16
    lines.append("// All polygon vertices: interleaved [lon×100, lat×100] pairs.")
    lines.append("// Rings within a zone are separated by sentinel (32767, 32767).")
    lines.append("static const int16_t TZ_POINTS[] PROGMEM = {")
    flat = []
    for ix, iy in all_points:
        flat.append(ix)
        flat.append(iy)
    for row in chunks(flat, 16):
        lines.append("  " + ", ".join(f"{v:6d}" for v in row) + ",")
    lines.append("};")
    lines.append("")

    # ── Zone struct ──────────────────────────────────────────────
    lines.append("typedef struct {")
    lines.append("  char           tzid[40];      // IANA timezone id")
    lines.append("  char           country[4];    // ISO 3166-1 alpha-2")
    lines.append("  int16_t        bbox[4];        // lon_min,lat_min,lon_max,lat_max (×100)")
    lines.append("  uint16_t       pt_start;       // index into TZ_POINTS (pair index)")
    lines.append("  uint16_t       pt_end;         // exclusive end")
    lines.append("  uint8_t        ring_count;     // number of rings")
    lines.append("  uint8_t        has_dst;")
    lines.append("  int16_t        utc_std;        // UTC offset standard × 100 (minutes*100/60)")
    lines.append("  int16_t        utc_dst;        // UTC offset DST × 100")
    lines.append("  int16_t        dst_offset;     // shift magnitude × 100")
    lines.append("  char           abbr_std[10];")
    lines.append("  char           abbr_dst[10];")
    lines.append("  uint8_t        dst_start[5];   // {month,week,dow,hour,min}")
    lines.append("  uint8_t        dst_end[5];     // {month,week,dow,hour,min}")
    lines.append("} TzZone;")
    lines.append("")

    # ── Zone array ───────────────────────────────────────────────
    lines.append("static const TzZone TZ_ZONES[] PROGMEM = {")
    for z in zone_metas:
        b = z["bbox"]
        ds = z["dst_start"]
        de = z["dst_end"]
        lines.append(f'  {{ "{z["tzid"]}", "{z["country"]}", '
                     f'{{{b[0]},{b[1]},{b[2]},{b[3]}}}, '
                     f'{z["start_idx"]}, {z["end_idx"]}, '
                     f'{z["ring_count"]}, '
                     f'{1 if z["has_dst"] else 0}, '
                     f'{z["utc_std"]}, {z["utc_dst"]}, {z["dst_off"]}, '
                     f'"{z["abbr_std"]}", "{z["abbr_dst"]}", '
                     f'{{{ds[0]},{ds[1]},{ds[2]},{ds[3]},{ds[4]}}}, '
                     f'{{{de[0]},{de[1]},{de[2]},{de[3]},{de[4]}}}  }},')
    lines.append("};")
    lines.append("")

    return "\n".join(lines)


# ─────────────────────────────────────────────────────────────────
# Generate timezone_lookup.h
# ─────────────────────────────────────────────────────────────────

LOOKUP_H = r"""// AUTO-GENERATED by geojson_to_arduino.py — DO NOT EDIT
// Timezone lookup by GPS coordinates for Arduino / ESP32 / ESP8266
//
// Include order in your .ino:
//   #include "timezone_data.h"   // <-- FIRST (defines PROGMEM stubs + data)
//   #include "timezone_lookup.h" // <-- SECOND
//
// Usage:
//   TzResult r = tz_lookup(48.8566f, 2.3522f, 2026, 3, 29, 3, 0);
//   if (r.valid) {
//     Serial.println(r.country);      // "FR"
//     Serial.println(r.abbr);         // "CEST"
//     Serial.print(r.utc_offset_h);   // 2.0  (float, hours)
//   }
#pragma once
// timezone_data.h must be included BEFORE this file — it defines
// TzZone, TZ_ZONES, TZ_POINTS, TZ_ZONE_COUNT and all PROGMEM helpers.
#include <stdint.h>
#include <string.h>

// ── Result structure ────────────────────────────────────────────
typedef struct {
  uint8_t  valid;           // 1 = found, 0 = no zone at these coordinates
  char     country[4];      // ISO 3166-1 alpha-2, e.g. "DE"
  char     tzid[40];        // IANA id, e.g. "Europe/Berlin"
  char     abbr[10];        // time abbreviation, e.g. "CEST"
  float    utc_offset_h;    // current UTC offset in hours, e.g. 2.0
  uint8_t  is_dst;          // 1 if DST is currently active
} TzResult;

// ── PROGMEM helpers ─────────────────────────────────────────────
static inline int16_t _tz_pt(uint16_t pair_idx, uint8_t component) {
    return (int16_t)pgm_read_word(&TZ_POINTS[pair_idx * 2 + component]);
}

static inline void _tz_read_zone(uint16_t i, TzZone* out) {
    memcpy_P(out, &TZ_ZONES[i], sizeof(TzZone));
}

// ── DST active check ────────────────────────────────────────────
static uint8_t _tz_rule_day(const uint8_t rule[5], uint16_t year) {
    uint8_t month = rule[0];
    uint8_t week  = rule[1];
    uint8_t dow   = rule[2];  // POSIX: 0=Sun, 1=Mon ... 6=Sat

    uint8_t m = month;
    uint16_t y = year;
    if (m < 3) { m += 12; y--; }
    uint8_t first_dow = (uint8_t)((1 + (13*(m+1))/5 + y + y/4 - y/100 + y/400) % 7);

    int8_t diff = (int8_t)dow - (int8_t)first_dow;
    if (diff < 0) diff += 7;
    uint8_t day = 1 + (uint8_t)diff;

    if (week == 5) {
        static const uint8_t mdays[13] = {0,31,28,31,30,31,30,31,31,30,31,30,31};
        uint8_t max_day = mdays[month];
        if (month == 2 && ((year%4==0 && year%100!=0) || year%400==0)) max_day = 29;
        while (day + 7 <= max_day) day += 7;
    } else {
        day += 7 * (week - 1);
    }
    return day;
}

static uint8_t _tz_is_dst(const TzZone* z,
                           uint16_t year, uint8_t month, uint8_t mday,
                           uint8_t hour, uint8_t minute) {
    if (!z->has_dst) return 0;

    const uint8_t* rs = z->dst_start;
    const uint8_t* re = z->dst_end;
    if (rs[0] == 0 || re[0] == 0) return 0;

    uint8_t start_day = _tz_rule_day(rs, year);
    uint8_t end_day   = _tz_rule_day(re, year);

    static const uint16_t mstart[13] = {
        0, 0, 31, 59, 90, 120, 151, 181, 212, 243, 273, 304, 334
    };
    uint32_t now   = (uint32_t)(mstart[month]   + mday      - 1) * 1440 + hour * 60 + minute;
    uint32_t t_on  = (uint32_t)(mstart[rs[0]]   + start_day - 1) * 1440 + rs[3] * 60 + rs[4];
    uint32_t t_off = (uint32_t)(mstart[re[0]]   + end_day   - 1) * 1440 + re[3] * 60 + re[4];

    if (t_on < t_off) {
        return (now >= t_on && now < t_off) ? 1 : 0;
    } else {
        return (now >= t_on || now < t_off) ? 1 : 0;
    }
}

// ── Ray-casting point-in-polygon ────────────────────────────────
static uint8_t _tz_pip_ring(int32_t ilon, int32_t ilat,
                             uint16_t pt_start, uint16_t pt_end) {
    uint8_t  inside = 0;
    uint16_t n = pt_end - pt_start;
    if (n < 3) return 0;

    uint16_t j = n - 1;
    for (uint16_t i = 0; i < n; i++) {
        int32_t xi = _tz_pt(pt_start + i, 0);
        int32_t yi = _tz_pt(pt_start + i, 1);
        int32_t xj = _tz_pt(pt_start + j, 0);
        int32_t yj = _tz_pt(pt_start + j, 1);

        if (xi == 32767 || xj == 32767) { j = i; continue; }

        if (((yi > ilat) != (yj > ilat)) &&
            (ilon < (xj - xi) * (ilat - yi) / (yj - yi) + xi)) {
            inside ^= 1;
        }
        j = i;
    }
    return inside;
}

static uint8_t _tz_point_in_zone(int32_t ilon, int32_t ilat, const TzZone* z) {
    uint16_t ps = z->pt_start;
    uint16_t pe = z->pt_end;

    if (ilon < z->bbox[0] || ilon > z->bbox[2]) return 0;
    if (ilat < z->bbox[1] || ilat > z->bbox[3]) return 0;

    uint16_t ring_start = ps;
    uint8_t  in_any     = 0;

    for (uint16_t k = ps; k < pe; k++) {
        int16_t x = _tz_pt(k, 0);
        int16_t y = _tz_pt(k, 1);
        if (x == 32767 && y == 32767) {
            if (_tz_pip_ring(ilon, ilat, ring_start, k)) in_any = 1;
            ring_start = k + 1;
        }
    }
    if (_tz_pip_ring(ilon, ilat, ring_start, pe)) in_any = 1;
    return in_any;
}

// ── Public API ──────────────────────────────────────────────────
/**
 * tz_lookup — find timezone for GPS coordinates.
 *
 * @param lat      Latitude  (+N / -S)
 * @param lon      Longitude (+E / -W)
 * @param year     4-digit year,  e.g. 2026
 * @param month    Month 1-12
 * @param mday     Day of month 1-31
 * @param hour     Hour 0-23  (UTC)
 * @param minute   Minute 0-59
 * @return TzResult  (.valid==0 if point is in no timezone polygon)
 *
 * Example:
 *   TzResult r = tz_lookup(52.52f, 13.405f, 2026, 6, 15, 10, 0);
 *   // r.country="DE", r.abbr="CEST", r.utc_offset_h=2.0, r.is_dst=1
 */
static TzResult tz_lookup(float lat, float lon,
                           uint16_t year, uint8_t month, uint8_t mday,
                           uint8_t hour, uint8_t minute) {
    TzResult result;
    memset(&result, 0, sizeof(result));

    int32_t ilon = (int32_t)(lon * 100.0f + (lon >= 0 ? 0.5f : -0.5f));
    int32_t ilat = (int32_t)(lat * 100.0f + (lat >= 0 ? 0.5f : -0.5f));

    TzZone z;
    for (uint16_t i = 0; i < TZ_ZONE_COUNT; i++) {
        _tz_read_zone(i, &z);
        if (!_tz_point_in_zone(ilon, ilat, &z)) continue;

        result.valid = 1;
        strncpy(result.country, z.country, sizeof(result.country) - 1);
        strncpy(result.tzid,    z.tzid,    sizeof(result.tzid)    - 1);

        uint8_t dst_active  = _tz_is_dst(&z, year, month, mday, hour, minute);
        result.is_dst       = dst_active;
        int16_t off_raw     = dst_active ? z.utc_dst : z.utc_std;
        result.utc_offset_h = off_raw / 100.0f;
        strncpy(result.abbr,
                dst_active ? z.abbr_dst : z.abbr_std,
                sizeof(result.abbr) - 1);
        return result;
    }
    return result;  // valid == 0
}
"""


# ─────────────────────────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────────────────────────

def main():
    ap = argparse.ArgumentParser(
        description="Converts timezones_dst.geojson → Arduino .h files"
    )
    ap.add_argument("--input",      default="timezones_dst.geojson",
                    help="Input GeoJSON file")
    ap.add_argument("--out-data",   default="timezone_data.h",
                    help="Output data file")
    ap.add_argument("--out-lookup", default="timezone_lookup.h",
                    help="Output lookup algorithm file")
    ap.add_argument("--max-pts",    type=int, default=120,
                    help="Max points per ring (fewer → less Flash). "
                         "Recommendations: UNO=40, Mega=80, ESP8266=120, ESP32=200")
    args = ap.parse_args()

    inp = Path(args.input)
    if not inp.exists():
        print(f"❌ File not found: {inp}", file=sys.stderr)
        sys.exit(1)

    print(f"📖 Reading {inp} ...")
    with open(inp, encoding="utf-8") as f:
        data = json.load(f)

    features = data.get("features", [])
    print(f"   Features loaded: {len(features)}")

    # ── timezone_data.h ──
    print(f"⚙  Generating {args.out_data} (max {args.max_pts} points/ring) ...")
    data_h = build_data_header(features, args.max_pts)
    out_data = Path(args.out_data)
    out_data.write_text(data_h, encoding="utf-8")
    kb = out_data.stat().st_size / 1024
    print(f"   ✔ {out_data}  ({kb:.1f} KB)")

    # ── timezone_lookup.h ──
    out_lookup = Path(args.out_lookup)
    out_lookup.write_text(LOOKUP_H, encoding="utf-8")
    kb2 = out_lookup.stat().st_size / 1024
    print(f"   ✔ {out_lookup}  ({kb2:.1f} KB)")

    print()
    print("═" * 60)
    print("  ✅ Done!")
    print()
    print("  Include in your Arduino sketch:")
    print(f"    #include \"{out_data.name}\"")
    print(f"    #include \"{out_lookup.name}\"")
    print()
    print("  Example call:")
    print("    TzResult r = tz_lookup(52.52f, 13.405f,")
    print("                           2026, 6, 15, 10, 0);")
    print("    if (r.valid) {")
    print("      Serial.println(r.country);     // \"DE\"")
    print("      Serial.println(r.abbr);        // \"CEST\"")
    print("      Serial.println(r.utc_offset_h);// 2.0")
    print("      Serial.println(r.is_dst);      // 1")
    print("    }")
    print()
    print("  Recommended --max-pts by platform:")
    print("    Arduino UNO/Nano  (32KB Flash)  : --max-pts 35")
    print("    Arduino Mega      (256KB Flash) : --max-pts 80")
    print("    ESP8266           (1MB Flash)   : --max-pts 120")
    print("    ESP32             (4MB Flash)   : --max-pts 200")
    print("═" * 60)


if __name__ == "__main__":
    main()
